#! /bin/bash
# A simple script that changes the brightness of the microphone indicator on window managers on huawei laptops
stateraw=$(light -Gs sysfs/leds/platform::micmute)
state=${stateraw%.*}
if [[ $state -eq 0 ]]; then
	light -Ss sysfs/leds/platform::micmute 100
else
	light -Ss sysfs/leds/platform::micmute 0
fi

