#!/usr/bin/bash

config=$HOME/.config/hypr
scripts=$config/scripts

hyprpaper &

dunst &

$scripts/restart-waybar &

## make kde connect work  (source: https://www.reddit.com/r/kde/comments/l6t6qu/please_make_kdeconnectcli_work_in_headless_moded/)
#/usr/lib/kdeconnectd -platform offscreen & 
## Gnome authentication
#/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

$scripts/micbacklight
